sudo: required
services:
  - docker

before_install:
  - docker build -t ajay291491/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajay291491/react-test npm test -- --coverage

after_success:
  - docker build -t ajay291491/multi-client ./client
  - docker build -t ajay291491/multi-server ./server
  - docker build -t ajay291491/multi-nginx ./nginx
  - docker build -t ajay291491/multi-worker ./worker
  # upload to docker repo by login to docker cli
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin 
  # Push the imags to docker hub
  - docker push ajay291491/multi-client
  - docker push ajay291491/multi-server
  - docker push ajay291491/multi-nginx
  - docker push ajay291491/multi-worker
